### ISSUE TITLE
Temp. redirect not working

### ISSUE THREAD

**Issue by robo81** [EpicPilgrim/302-instead#1]
As of version 1.8.1, temp redirects do not work.
I also confirmed this by analyzing the redirect on redirect-checker.org

Please update plugin!
Thnx!!!!

**Comment by EpicPilgrim** [comment]
Thanks for letting me know, @robo81 . I don't currently have time to work on this but when we do our next upgrade of yourls, will test this and release a patch (unless someone beats me to the patch).

**Comment by EpicPilgrim** [comment]
@robo81 as per above, fix by @Dullage has been merged in
